# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import observer_pb2 as observer__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in observer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataObserverStub(object):
    """Define the gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObserveData = channel.unary_unary(
                '/protos.DataObserver/ObserveData',
                request_serializer=observer__pb2.ObservationRequest.SerializeToString,
                response_deserializer=observer__pb2.ObservationResponse.FromString,
                _registered_method=True)


class DataObserverServicer(object):
    """Define the gRPC service
    """

    def ObserveData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataObserverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObserveData': grpc.unary_unary_rpc_method_handler(
                    servicer.ObserveData,
                    request_deserializer=observer__pb2.ObservationRequest.FromString,
                    response_serializer=observer__pb2.ObservationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.DataObserver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protos.DataObserver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataObserver(object):
    """Define the gRPC service
    """

    @staticmethod
    def ObserveData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.DataObserver/ObserveData',
            observer__pb2.ObservationRequest.SerializeToString,
            observer__pb2.ObservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
